version: '3'

services:
  app:
    image: jhonatanpatrocinio/codeeducation:app_node
    container_name: app_node
    entrypoint: dockerize -wait tcp://db_node:3306 -timeout 120s docker-entrypoint.sh
    command: bash -c "node index.js"
    networks: 
      - node-network
    tty: true
    depends_on: 
      - db
  db:
    image: jhonatanpatrocinio/codeeducation:db_node
    command: --innodb-use-native-aio=0 --default-authentication-plugin=mysql_native_password
    container_name: db_node
    restart: always
    tty: true
    volumes: 
      - ./mysql_data:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: node
      MYSQL_PASSWORD: root
    networks: 
      - node-network

  nginx:
    image: jhonatanpatrocinio/codeeducation:nginx_node
    container_name: nginx_node
    entrypoint: dockerize -wait http://app_node:3000/ -timeout 120s nginx -g 'daemon off';
    tty: true
    depends_on: 
      - db
      - app
    networks:
      - node-network
    ports: 
      - "8080:80"

networks: 
  node-network:
    driver: bridge   

